version: '3.8'

volumes:
  postgres_data:
      driver: local

services:
  postgres-ecard:
      container_name: postgres-ecard
      image: postgres:15.2      
      volumes:
        - postgres_ecard_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ecard
        POSTGRES_USER: ecard
        POSTGRES_PASSWORD: ecard@123
      ports:
        - 5432:5432
#      healthcheck:
#        test: ["CMD-SHELL", "pg_isready -d keycloak -U keycloak"]
#        interval: 10s
#        timeout: 3s
#        retries: 3
#  ecard-poc:
#    image: ecard-poc
#    container_name: ecard-poc
#    environment:
#      POSTGRES_DATABASE_HOST: postgres-ecard
#    env_file:
#      - src/main/resources/local.env
#    ports:
#      - 8002:8002
#    depends_on:
#      - postgres-ecard

# Persisted data across application restarts
volumes:
  postgres_ecard_data: {}
#  cache:
#    driver: local


