server:
  port: 8082
  #  ${ECARD_SERVICE_PROVIDER_PORT}
  servlet:
    context-path: '/ecard'
#logging.level.root: DEBUG

spring:
  datasource:
#    url: jdbc:postgresql://${POSTGRES_DATABASE_HOST}:5432/ecard
    url: jdbc:postgresql://localhost:5432/ecard
    username: ecard
    password: ecard@123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    hibernate.default_schema: public
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.format_sql: true
    properties.hibernate.jdbc.time_zone: UTC


twilio:
  account_sid: AC9b73c9aeef67da94082542f3629cfcc9
  auth_token: bf9f80ee9706b026f534c39c8d8230f8
  trial_number: +17402453676

#    properties.org.hibernate.envers.audit_table_prefix: AUD_
#    properties.org.hibernate.envers.audit_table_suffix:
#  quartz:
#    properties:
#      org:
#        quartz:
#          jobStore:
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#            isClustered: 'true'
#          scheduler:
#            instanceId: AUTO
#    job-store-type: jdbc
#    overwrite-existing-jobs: 'true'

#  liquibase:
#    enabled: true
#    change-log: classpath:changelog/db.changelog-master.xml

